Dawaly/Models/Place.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dawaly.Models
{
    public class Place
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="Home Type")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Details")]
        public string Details { get; set; }
        [Required]
        [Display(Name = "Location")]
        public string Location { get; set; }
        [Required]
        [Display(Name = "Price")]
        public double Price { get; set; }
        [Display(Name = "Image")]
        public string Image { get; set; }

        [Display(Name = "Type")]
        public int CategoryId { get; set; }

        public string UserID { get; set; }
        public virtual Category Category { get; set; }
        public virtual ApplicationUser User { get; set; }



    }
}

Dawaly/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dawaly.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Dawaly.Controllers
{
    [Authorize(Roles = "publisher,Admins")]
    public class PlacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Places
        public ActionResult Index()
        {
            var places = db.Places.Include(p => p.Category);
            return View(places.ToList());
        }

        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // GET: Places/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategortName");
            return View();
        }

        // POST: Places/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Place place , HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                place.Image = upload.FileName;
                place.UserID = User.Identity.GetUserId();
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategortName", place.CategoryId);
            return View(place);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategortName", place.CategoryId);
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Place place, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldImage = Path.Combine(Server.MapPath("~/Uploads"), place.Image);
                if (upload != null){
                System.IO.File.Delete(oldImage);
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                place.Image = upload.FileName;
                }
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
                
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategortName", place.CategoryId);
            return View(place);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dawaly/Views/Places/Create.cshtml
@model Dawaly.Models.Place

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default" style="background-color: black;
      height:60px; padding-left: 15px; padding-right: 15px;">
    <h3 class="panel-heading">Create New Place</h3>
</div>

@using (Html.BeginForm("Create", "Places", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal panel panel-default"
         style="background-color:black;padding-left:15px;
 padding-right:15px;padding-bottom:10px;padding-top:10px">
        <div class="h5 panel-heading" style="text-align-last:left">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="upload" />
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, "Place", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary"
                           style="color:black" />
                </div>
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Dawaly/Views/Places/Delete.cshtml
@model Dawaly.Models.Place

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel panel-default" style="background-color: black;
      height:60px; padding-left: 15px; padding-right: 15px;">
    <h3 class="panel-heading">Are you sure you want to delete this? </h3>
</div>
<div class="panel panel-default h5" style="background-color:black;
 padding-left:15px;padding-right:15px;padding-bottom:10px;
 padding-top:10px">
   
    <dl class="dl-horizontal  panel-heading" style="text-align-last:left">
        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Category.CategortName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategortName)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.Image)"
                 class="thumbnail" style="width:100px ; height:100px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Dawaly/Views/Places/Details.cshtml
@model Dawaly.Models.Place

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default" style="background-color: black;
      height:60px; padding-left: 15px; padding-right: 15px;">
    <h3 class="panel-heading"> Details Place </h3>
</div>
<div class="panel panel-default" style="background-color:black;
 padding-left:15px;padding-right:15px;padding-bottom:10px;
 padding-top:10px">
    <dl class="dl-horizontal h5 panel-heading" style="text-align-last:left">
        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Category.CategortName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategortName)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt style="height: 50px;">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.Image)"
                 class="thumbnail" style="width:100px ; height:100px;" />
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id}, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Dawaly/Views/Places/Edit.cshtml
@model Dawaly.Models.Place

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default" style="background-color: black;
      height:60px; padding-left: 15px; padding-right: 15px;">
    <h3 class="panel-heading">Edit</h3>
</div>

@using (Html.BeginForm("Edit", "Places", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal panel panel-default"
         style="background-color:black;padding-left:15px;
 padding-right:15px;padding-bottom:10px;padding-top:10px">
        <div class="h5 panel-heading" style="text-align-last:left">

            <div class="alert alert-danger" id="errmassege" style="display:none">
                <span id="view-err">

                </span>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Image)
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="upload" id="PlaceImage" />
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-info" id="save" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{
    <script>
        $(function () {
            $("#save").click(function () {
                if ($("#PlaceImage").val() !== "") {
                    var filename = document.getElementById("PlaceImage").value;
                    var extentionImage = filename.substr(filename.lastIndexOf('.') + 1);
                    var validextention = ['jpg', 'png'];
                    if ($.inArray(extentionImage, validextention) == -1) {
                        $("#errmassege").fadeIn();
                        $("#view-err").append("Pleace Select extention Image corect");
                        return false;
                    }
                }
            });
        });
    </script>
}

Dawaly/Views/Places/Index.cshtml
@model IEnumerable<Dawaly.Models.Place>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default" style="background-color:black;
     padding-top:10px;padding-left: 15px;padding-right: 15px;
     ">
    <div class="col-1 panel panel-heading ">
        <h3>Places</h3>
        <h4>@Html.ActionLink("Create New Place", "Create", new { @class = "btn btn-primary" })</h4>
    </div>
</div>
<div class="panel panel-default" style="background-color:black;
 padding-left:15px;padding-right:15px;padding-bottom:10px;padding-top:10px">

    <table class="table h5 panel-heading">
            <tr>
                <th>
                  Name
                </th>
                <th>
                   Name
                </th>
                <th>
                   Details
                </th>
                <th>
                   Location
                </th>
                <th>
                   Price
                </th>
                <th>
                    Image
                </th>
                <th></th>
            </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.CategortName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <img src="~/Uploads/@Html.DisplayFor(modelItem=>item.Image)"
                         class="thumbnail" style="width:100px ; height:100px;" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

</div>